FROM python:3.11-slim

WORKDIR /app

COPY requirements-api.txt /app/requirements-api.txt
RUN pip install --no-cache-dir -r /app/requirements-api.txt

COPY ecg_artifact_filter.py /app/ecg_artifact_filter.py
COPY service_api /app/service_api
COPY artifacts /app/artifacts

EXPOSE 8000

ENV MODEL_PATH=artifacts/ecg_rf_artifact_model_labelstudio.joblib

CMD ["uvicorn", "service_api.main:app", "--host", "0.0.0.0", "--port", "8000"]
