#! /bin/bash

DOCKER_NAME="cde_serov"  
CONTAINER_NAME=$USER"-cde_serov" 
SRC=$(pwd)

DOCKER_USER_ID=$(id -u)
DOCKER_GROUP_ID=$(id -g)

echo "--- Config Loaded ---"
echo "User ID: $DOCKER_USER_ID, Group ID: $DOCKER_GROUP_ID"
echo "Project Path: $SRC"
echo "---------------------"